[package]
name = "SolaceInSolitude"
version = "0.1.0"
edition = "2024"
authors = ["Hopeflea", "Syborg64"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
debug = "line-tables-only"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
debug = false

[profile.debugging]
inherits = "dev"
debug = true

[features]
editor = ["dep:bevy_editor"]

# [patch."https://github.com/Agartha-Software/bevy_editor_prototypes.git"]
# bevy_editor = { path = "../bevy_editor_prototypes/crates/bevy_editor", version = "0.1.0" }

[dependencies]
bevy = { git = "https://github.com/cart/bevy.git", rev = "87a21ecafa51bfaea02834b5933f08397b45b984", features = [
    "dynamic_linking",
    "wav",
    "mp3",
    "bevy_ui_debug",
    "bevy_dev_tools",
] }
bevy_editor = { git = "https://github.com/Agartha-Software/bevy_editor_prototypes.git", version = "0.1.0", optional = true }
rand = "0.10.0"
